language: c
sudo: false
install: true
addons:
  apt:
    packages:
    - rubber
    - latex-beamer
    - xsltproc
script:
- ./t/0001-who-is-this
- ./t/0002-rubber-pdf-doc
- ./t/0004-static-pages
- rm -f doc/*.{aux,log,nav,out,snm,toc,bak}
- ./t/0006-docs-deploy
env:
  global:
    secure: ABOyq5RiOFKhVczolqbfgGD6ahwEWqHA6i3Hg9iHsuchmkmHvdqtK79D/1+eGsTwRKQ4GDQbhSUXxwURlc/mIb1hhksnBFU43Qo+G0mVJYidQxxwvlIyIRolwk9gJ1WRCzAptjFuSSJngA8wE0c3RhCyPhgQKxCXdIH/Zpsvhwkw6x8OA2s0femm7RTaxWnO4hb0TjTqRK65WYTSqjqo1Tnzo6RzL969/p5Nct46uBJB/vgWsAUajlaI5aORiK2AkDprywyJ7heaLicVtCS49yKEXv3h2G358jOxGDypngYPWOo6Y9FSV2Aw67HWuo3nGNpg46SOMLmfY/6aG14KjlZJZ5B0MWJgVJ0VJeP58fP3CohDybRN8A+u3pzN9eSqB7L6J+LBjHcXMqNceeyhiDhwxHp/YgaMKqIdz0B+eIQt389ihkFqwykRjtbNXFL58p+JoX/ZDp23PmXOJmlbLca1oyOn3clUr2J2inBdlaM05vdTRtTVASGJtIBntCJFHaEifiaO6ose+fwOwITW4Kn4gg5zIY+AOtEetQq8f5pHQ/Oq5Qy2d55hlrXVNaMNFrDSQd1Wp8gsOPKr3GXSGoQswHSuOTnrYeD4b+idrijeNrZJQsPqH/X2R1/ZSEe+UtNiuM5g6DDptzWXYSyLkZeC29aGf7+zCGbs5U/bZkA=
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  on:
    branch: feature/0006/static-pages
  verbose: true
  local-dir: ./docs/
  github-token:
    secure: Zs4E5TSBCsq+F71A02zlIUxvhrtz/tOyIUSYYAoN0HYXxwDYL6wRKUrDvkEwtwjmS9IfCy+R4k9cClipiLbQLtJpIayh5qz0T0XYrIGi7+rm4i9sSOrrSk6AuCQ/yYpPqXD/dSe0kTmw8vgfqgbBoXYZG/xEiNEp430FvjRjx+bprLIbn+G5mtFDYiWCP7z5DQ5buFUte8kMzopmYvZZYstRrys7vlNkN/J9BrqD2z1YBYqv2SKMfTTHIEVulmVCfymOfUfsBdBsD2tYJejnZvaJELsMt20+7pO3lhtM4i/hDER/nSWePzs9/qRYwU8Ymdoe+eTSBvnrLshiQmvXFIjAHflYXsKjy6tcYp/SYYEtK4nXY1NpUbw6B8tam/hNMCNCQuhu8sqL5T7xKI2rTna7eN5uxrdgSv7N06zK+1je23pXYPu2oJoEZADrnGF4+wt94fOYOj6YK212RpZ9PlT4uzaKVIZ/z4LydT2cATeAPaBeACWtMnKGrLiLF5hcaRrj/H2j0yIht7OCG4ivRLl4JcgUO9jiS883jXPwDKRfL/94ffjeeAFsxqZbj560VbVXt71DjHr1itySH1OBQaJISDJ91F64QGRVARIZn+5fgNmBeiW3VNqVLorLblkHd3dRRpjxh0Aj6zGZjVxoVPlqUZa1XJZYTVLqSalfO6E=
